
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS02:1433;databaseName=BRMS_DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=true


spring.application.name=BRMS-Application