
spring.application.name=BRMS-Application

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost\\SQLEXPRESS02:1433;databaseName=BRMS_DB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
